
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Checkbutton


OUTPUT_PATH = Path(__file__).parent
ASSETS_FOLDER = "assets/frame0"
ASSETS_PATH = OUTPUT_PATH / ASSETS_FOLDER

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("973x605")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 605,
    width = 973,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    973.0,
    73.0,
    fill="#1EBA65",
    outline="")

canvas.create_text(
    266.0,
    27.0,
    anchor="nw",
    text="Ecaddy - outil de shopping pour le matériel informatique",
    fill="#FFFFFF",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    31.0,
    116.0,
    anchor="nw",
    text="CHOISIR DES PRODUITS",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    770.0,
    177.0,
    anchor="nw",
    text="Alternate",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    667.0,
    116.0,
    anchor="nw",
    text="CHOISIR DES MAGASINS",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=309.0,
    y=240.0,
    width=28.0,
    height=28.0
)

canvas.create_text(
    770.0,
    225.0,
    anchor="nw",
    text="Boulanger",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    770.0,
    273.0,
    anchor="nw",
    text="CyberTech",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    770.0,
    321.0,
    anchor="nw",
    text="GrosBill",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)

canvas.create_text(
    770.0,
    369.0,
    anchor="nw",
    text="Materiel.net",
    fill="#000000",
    font=("Inter Bold", 16 * -1)
)
#checkboxes
checkbox_1 = Checkbutton(window, width=28, height=28, bg="#D3D3D3", highlightbackground="#D3D3D3")
checkbox_1.place(x=715.0, y=220.0)

checkbox_2 = Checkbutton(window, width=28, height=28, bg="#D3D3D3", highlightbackground="#D3D3D3")
checkbox_2.place(x=715.0, y=268.0)

checkbox_3 = Checkbutton(window, width=28, height=28, bg="#D3D3D3", highlightbackground="#D3D3D3")
checkbox_3.place(x=715.0, y=316.0)

checkbox_4 = Checkbutton(window, width=28, height=28, bg="#D3D3D3", highlightbackground="#D3D3D3")
checkbox_4.place(x=715.0, y=364.0)

checkbox_5 = Checkbutton(window, width=28, height=28, bg="#D3D3D3", highlightbackground="#D3D3D3")
checkbox_5.place(x=715.0, y=172.0)

canvas.create_rectangle(
    641.0,
    66.0,
    647.0000000000001,
    650.0216064453125,
    fill="#1EBA65",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    219.5,
    186.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D3D3D3",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=120.0,
    y=172.0,
    width=199.0,
    height=26.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    411.0,
    186.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D3D3D3",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=356.0,
    y=172.0,
    width=110.0,
    height=26.0
)

canvas.create_text(
    114.0,
    152.0,
    anchor="nw",
    text="Nom du produit *",
    fill="#000000",
    font=("Inter Medium", 14 * -1)
)

canvas.create_text(
    350.0,
    152.0,
    anchor="nw",
    text="Marque",
    fill="#000000",
    font=("Inter Medium", 14 * -1)
)

canvas.create_text(
    504.0,
    149.0,
    anchor="nw",
    text="Quantité",
    fill="#000000",
    font=("Inter Medium", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=58.0,
    y=172.0,
    width=28.0,
    height=28.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=570.0,
    y=172.0,
    width=28.0,
    height=28.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=504.0,
    y=172.0,
    width=28.0,
    height=28.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    551.0,
    186.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D3D3D3",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=544.0,
    y=172.0,
    width=14.0,
    height=26.0
)

canvas.create_rectangle(
    81.0,
    217.9999999999999,
    556.0,
    219.0,
    fill="#1EBA65",
    outline="")

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=670.0,
    y=509.0,
    width=174.0,
    height=64.0
)
window.resizable(False, False)
window.mainloop()
